// This file is auto-generated by @hey-api/openapi-ts

export type CobblesModel = {
    crew: string;
    cobbles: number;
};

export type IncidentEditModel = {
    startDate: string;
    stopDate: string;
    aCrew: number;
    bCrew: number;
    cCrew: number;
    dCrew: number;
    dayCrew: number;
};

export type MeasurementModel = {
    typeId?: number;
    reading?: number;
    takenAt?: string;
};

export type MeasurementTypeModel = {
    id?: number;
    name?: string | null;
    unit?: string | null;
    capacity?: number;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

export type ProductionBonusEditModel = {
    id?: number;
    startDate?: string;
    stopDate?: string;
    aCrew?: number;
    bCrew?: number;
    cCrew?: number;
    dCrew?: number;
    average?: number;
};

export type RunningBonusModel = {
    crew: string;
    runningBonus: number;
    totalHours: number;
};

export type StarsByCrewModel = {
    crew: string;
    starCount: number;
};

export type TheoreticalBonusRequest = {
    productionBonus?: Array<RunningBonusModel>;
    startDate?: string;
    stopDate?: string;
};

export type TonsByCrewModel = {
    crew: string;
    tons: number;
};

export type WorkOrderModel = {
    id?: number;
    name?: string | null;
    summarynote?: string | null;
    memo?: string | null;
    eventdate?: string | null;
};

export type YieldByCrewModel = {
    crew: string;
    weeklyYield: number;
    ytdYield: number;
};

export type GetStarsByCrewData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/stars-by-crew';
};

export type GetStarsByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetStarsByCrewError = GetStarsByCrewErrors[keyof GetStarsByCrewErrors];

export type GetStarsByCrewResponses = {
    /**
     * OK
     */
    200: Array<StarsByCrewModel>;
};

export type GetStarsByCrewResponse = GetStarsByCrewResponses[keyof GetStarsByCrewResponses];

export type GetBundledTonsByCrewData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/bundled-tons-by-crew';
};

export type GetBundledTonsByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetBundledTonsByCrewError = GetBundledTonsByCrewErrors[keyof GetBundledTonsByCrewErrors];

export type GetBundledTonsByCrewResponses = {
    /**
     * OK
     */
    200: Array<TonsByCrewModel>;
};

export type GetBundledTonsByCrewResponse = GetBundledTonsByCrewResponses[keyof GetBundledTonsByCrewResponses];

export type GetRolledTonsByCrewData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/rolled-tons-by-crew';
};

export type GetRolledTonsByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetRolledTonsByCrewError = GetRolledTonsByCrewErrors[keyof GetRolledTonsByCrewErrors];

export type GetRolledTonsByCrewResponses = {
    /**
     * OK
     */
    200: Array<TonsByCrewModel>;
};

export type GetRolledTonsByCrewResponse = GetRolledTonsByCrewResponses[keyof GetRolledTonsByCrewResponses];

export type GetBloomYardScrapTonsByCrewData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/bloom-yard-scrap-tons-by-crew';
};

export type GetBloomYardScrapTonsByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetBloomYardScrapTonsByCrewError = GetBloomYardScrapTonsByCrewErrors[keyof GetBloomYardScrapTonsByCrewErrors];

export type GetBloomYardScrapTonsByCrewResponses = {
    /**
     * OK
     */
    200: Array<TonsByCrewModel>;
};

export type GetBloomYardScrapTonsByCrewResponse = GetBloomYardScrapTonsByCrewResponses[keyof GetBloomYardScrapTonsByCrewResponses];

export type GetBonusByCrewData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/bonus-by-crew';
};

export type GetBonusByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetBonusByCrewError = GetBonusByCrewErrors[keyof GetBonusByCrewErrors];

export type GetBonusByCrewResponses = {
    /**
     * OK
     */
    200: Array<RunningBonusModel>;
};

export type GetBonusByCrewResponse = GetBonusByCrewResponses[keyof GetBonusByCrewResponses];

export type MergeBonusByCrewData = {
    body: ProductionBonusEditModel;
    path?: never;
    query?: never;
    url: '/api/achievement/bonus-by-crew';
};

export type MergeBonusByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type MergeBonusByCrewError = MergeBonusByCrewErrors[keyof MergeBonusByCrewErrors];

export type MergeBonusByCrewResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type MergeBonusByCrewResponse = MergeBonusByCrewResponses[keyof MergeBonusByCrewResponses];

export type GetIncidentByCrewData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/incident-by-crew';
};

export type GetIncidentByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetIncidentByCrewError = GetIncidentByCrewErrors[keyof GetIncidentByCrewErrors];

export type GetIncidentByCrewResponses = {
    /**
     * OK
     */
    200: IncidentEditModel;
};

export type GetIncidentByCrewResponse = GetIncidentByCrewResponses[keyof GetIncidentByCrewResponses];

export type MergeIncidentByCrewData = {
    body: IncidentEditModel;
    path?: never;
    query?: never;
    url: '/api/achievement/incident-by-crew';
};

export type MergeIncidentByCrewErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type MergeIncidentByCrewError = MergeIncidentByCrewErrors[keyof MergeIncidentByCrewErrors];

export type MergeIncidentByCrewResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type MergeIncidentByCrewResponse = MergeIncidentByCrewResponses[keyof MergeIncidentByCrewResponses];

export type CalculateYieldsData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
        ytdStartDate: string;
    };
    url: '/api/achievement/yields';
};

export type CalculateYieldsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type CalculateYieldsError = CalculateYieldsErrors[keyof CalculateYieldsErrors];

export type CalculateYieldsResponses = {
    /**
     * OK
     */
    200: Array<YieldByCrewModel>;
};

export type CalculateYieldsResponse = CalculateYieldsResponses[keyof CalculateYieldsResponses];

export type GetCobblesData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/achievement/cobbles';
};

export type GetCobblesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetCobblesError = GetCobblesErrors[keyof GetCobblesErrors];

export type GetCobblesResponses = {
    /**
     * OK
     */
    200: Array<CobblesModel>;
};

export type GetCobblesResponse = GetCobblesResponses[keyof GetCobblesResponses];

export type CalculateTheoreticalBonusesData = {
    body: TheoreticalBonusRequest;
    path?: never;
    query?: never;
    url: '/api/achievement/theoretical-bonuses';
};

export type CalculateTheoreticalBonusesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type CalculateTheoreticalBonusesError = CalculateTheoreticalBonusesErrors[keyof CalculateTheoreticalBonusesErrors];

export type CalculateTheoreticalBonusesResponses = {
    /**
     * OK
     */
    200: Array<RunningBonusModel>;
};

export type CalculateTheoreticalBonusesResponse = CalculateTheoreticalBonusesResponses[keyof CalculateTheoreticalBonusesResponses];

export type GetMeasurementTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/measurement/types';
};

export type GetMeasurementTypesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetMeasurementTypesError = GetMeasurementTypesErrors[keyof GetMeasurementTypesErrors];

export type GetMeasurementTypesResponses = {
    /**
     * OK
     */
    200: Array<MeasurementTypeModel>;
};

export type GetMeasurementTypesResponse = GetMeasurementTypesResponses[keyof GetMeasurementTypesResponses];

export type GetLatestMeasurementsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/measurement/latest';
};

export type GetLatestMeasurementsErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetLatestMeasurementsError = GetLatestMeasurementsErrors[keyof GetLatestMeasurementsErrors];

export type GetLatestMeasurementsResponses = {
    /**
     * OK
     */
    200: Array<MeasurementModel>;
};

export type GetLatestMeasurementsResponse = GetLatestMeasurementsResponses[keyof GetLatestMeasurementsResponses];

export type GetHistoricalMeasurementsData = {
    body?: never;
    path: {
        typeId: number;
    };
    query?: {
        fromTime?: string;
    };
    url: '/api/measurement/historical/{typeId}';
};

export type GetHistoricalMeasurementsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetHistoricalMeasurementsError = GetHistoricalMeasurementsErrors[keyof GetHistoricalMeasurementsErrors];

export type GetHistoricalMeasurementsResponses = {
    /**
     * OK
     */
    200: Array<MeasurementModel>;
};

export type GetHistoricalMeasurementsResponse = GetHistoricalMeasurementsResponses[keyof GetHistoricalMeasurementsResponses];

export type GetMechanicalWorkOrdersData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        stopDate: string;
    };
    url: '/api/work-order/mechnical';
};

export type GetMechanicalWorkOrdersErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetMechanicalWorkOrdersError = GetMechanicalWorkOrdersErrors[keyof GetMechanicalWorkOrdersErrors];

export type GetMechanicalWorkOrdersResponses = {
    /**
     * OK
     */
    200: Array<WorkOrderModel>;
};

export type GetMechanicalWorkOrdersResponse = GetMechanicalWorkOrdersResponses[keyof GetMechanicalWorkOrdersResponses];

export type GetHomeSseEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sse/home-events';
};

export type GetHomeSseEventsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:52624/' | (string & {});
};